owner: actiun
repo: actiun-status

sites:
  - name: Actiun
    url: https://app.actiun.com
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/actiun/actiun-status/master/assets/actiun-favicon.ico
assignees:
  - JNajera
status-website:
  cname: status.actiun.com
  logoUrl: https://raw.githubusercontent.com/actiun/actiun-status/master/assets/actiun-logo.png
  favicon: https://raw.githubusercontent.com/actiun/actiun-status/master/assets/actiun-favicon.ico
  theme: light
  introTitle: "Sobre este sitio"
  introMessage: Bienvenido al monitor de estatus de Actiun. Aquí encontrarás información en tiempo real sobre el estado de nuestros servicios.
  navbar:
    - title: Estatus
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO